services:
  - type: web
    name: line-groupbot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app -w 1 -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: LINE_CHANNEL_SECRET
      - key: LINE_CHANNEL_ACCESS_TOKEN
